version: '3.9'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - grandma-scheduler
    volumes:
      - gm_postgres_data:/var/lib/postgresql/data

  scheduler:
    restart: always
    build: .
    depends_on:
      - postgres
      - mongo
    ports:
      - "3000:3000"
    networks:
      - grandma-scheduler
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo:6.0.1
    restart: always
    hostname: mongo
    environment:
      MONGO_REPLICA_HOST: mongo
      MONGO_REPLICA_PORT: 27017
    ports:
      - "27017:27017"
    networks:
      - grandma-scheduler
    volumes:
      - .:/usr/src/app
      - gm_mongo_data:/data/db
    command: bash -c "/usr/bin/mongod --replSet rs0 --bind_ip_all"

networks:
  grandma-scheduler:
    driver: bridge


volumes:
  gm_postgres_data:
  gm_mongo_data:
    driver: local
