version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - grandma-scheduler

  scheduler:
    restart: always
    build: .
    depends_on:
      - postgres
      - mongo
    ports:
      - "3000:3000"
    networks:
      - grandma-scheduler
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: TimeSeries
    ports:
      - "27017:27017"
    networks:
      - grandma-scheduler

networks:
  grandma-scheduler:
    driver: bridge

