version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - grandma-scheduler

  scheduler:
    restart: always
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - grandma-scheduler

networks:
  grandma-scheduler:
    driver: bridge

