version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - grandma-scheduler
    volumes:
      - gm_postgres_data:/var/lib/postgresql/data

  scheduler:
    restart: always
    build: .
    depends_on:
      - postgres
      - mongo
    ports:
      - "3000:3000"
    networks:
      - grandma-scheduler
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: TimeSeries
    ports:
      - "27017:27017"
    networks:
      - grandma-scheduler
    volumes:
      - gm_mongo_data:/data/db

networks:
  grandma-scheduler:
    driver: bridge


volumes:
  gm_postgres_data:
  gm_mongo_data:
    driver: local
